window.SITE_CONTENT = {
  home: {
    featuredProjects: ["diamond-continent-plus"],
    currentProjects: ["diamond-continent-plus", "site-archive"]
  },
  profile: {
    name: "哦里冻",
    handle: "ORITONG",
    avatar: "assets/avatar.jpg",
    role: "Minecraft 整合包制作者 · Blophy 官方谱师",
    intro: "尝试将所有能做的做到最好，但最后总是做成一团糟……",
    introduction: [
      "初次（也许不是）见面，欢迎来玩！",
      "尝试将所有能做的做到最好，但最后总是做成一团糟……",
      "喜欢充满了童话和梦想的世界，也想为你留住那一瞬的惊奇。",
      "平时制作 Minecraft 整合包，也担任游戏《Blophy》的官方谱师。",
      "图库里收着我的形象约稿，欢迎来看看不同画师笔下的我。"
    ],
    links: [
      { name: "Bilibili", label: "B 站", description: "视频与动态", url: "https://space.bilibili.com/494691236", mark: "B" },
      { name: "MC百科", label: "MC百科作者页", description: "整合包与 Minecraft 创作", url: "https://www.mcmod.cn/author/36024.html", mark: "MC" },
      { name: "GitHub", label: "GitHub", description: "开源项目与代码", url: "https://github.com/oritong", mark: "GH" },
      { name: "CurseForge", label: "CurseForge", description: "Minecraft 项目", url: "https://www.curseforge.com/members/oritong/projects", mark: "CF" },
      { name: "Modrinth", label: "Modrinth", description: "模组与整合包", url: "https://modrinth.com/user/oritong", mark: "MR" },
      { name: "XyeBBS", label: "XyeBBS", description: "社区主页", url: "https://www.xyebbs.com/members/49528", mark: "XY" },
      { name: "X", label: "X", description: "动态与近况", url: "https://x.com/_oritong_", mark: "X" },
      { name: "Discord", label: "Discord", description: "加入个人服务器", url: "https://discord.gg/4tR6FMmGJU", mark: "DC" }
    ],
    groups: [
      { label: "QQ 群", name: "我的 QQ 群", number: "946391190", description: "来群里找我玩" },
      { label: "Blophy 官方交流群", name: "Blophy 官方交流群", number: "761741595", description: "交流游戏与谱面" }
    ]
  },
  resources: [
    { name: "Wudji的k6教程（不全）", category: "教程：", description: "", url: "https://wudji.gitbook.io/xplus-kubejs-tutorial-v2-zh_cn", mark: "W" },
    { name: "孤梦的k6教程", category: "教程：", description: "", url: "https://gumeng.gitbook.io/kubejs-jiao-cheng-1.20.1", mark: "孤" },
    { name: "芒果佬的k6脚本", category: "教程：", description: "", url: "https://github.com/Mango-Minecraft-Project/Mango-KubeJScripts", mark: "芒" },
    { name: "现代工业化k7示例", category: "教程：", description: "", url: "https://github.com/AztechMC/Modern-Industrialization/tree/1.21.x/docs", mark: "MI" },
    { name: "MBD2wiki", category: "教程：", description: "", url: "https://github.com/Low-Drag-MC/Multiblocked2/wiki/", mark: "M2" },
    { name: "GTMwiki", category: "教程：", description: "过于老旧，建议读源码或者让AI帮你分析。", url: "https://gregtechceu.github.io/GregTech-Modern/1.20.1-7.5.3/Modpacks/", mark: "GTM" },
    { name: "数据包生成器", category: "工具：", description: "", url: "https://misode.github.io/", mark: "D" },
    { name: "种子查询（仅原版）", category: "工具：", description: "", url: "https://www.chunkbase.com/apps/seed-map", mark: "S" },
    { name: "在线格式转换", category: "工具：", description: "", url: "https://audio.online-convert.com/", mark: "音" },
    { name: "cf", category: "网站：", description: "", url: "https://www.curseforge.com/minecraft", mark: "CF" },
    { name: "mr", category: "网站：", description: "", url: "https://modrinth.com/discover/mods", mark: "MR" },
    { name: "github", category: "网站：", description: "", url: "https://github.com/", mark: "GH" },
    { name: "mcmod", category: "网站：", description: "", url: "https://www.mcmod.cn/", mark: "MC" },
    { name: "ds", category: "网站：", description: "", url: "https://chat.deepseek.com/", mark: "DS" },
    { name: "gpt", category: "网站：", description: "", url: "https://chatgpt.com/", mark: "GPT" },
    { name: "gemini", category: "网站：", description: "", url: "https://gemini.google.com/", mark: "G" },
    { name: "sunoAI", category: "网站：", description: "", url: "https://suno.com/about", mark: "S" }
  ],
  projects: [
    {
      id: "site-archive",
      name: "个人档案站",
      kind: "个人项目",
      status: "持续维护",
      year: "2026",
      summary: "将个人介绍、常用资源、项目记录和 Wiki 收在一个轻量的静态站点里。",
      tags: ["HTML", "CSS", "JavaScript", "GitHub Pages"],
      role: "设计与开发",
      outcome: "一个无需构建工具、可直接发布到 GitHub Pages 的个人知识入口。",
      pages: [
        { id: "overview", title: "项目概览", section: "01", body: ["这是一个纯静态的个人档案站点，包含个人介绍、资源索引、项目目录与 Wiki 页面。", "页面使用原生 HTML、CSS 和 JavaScript 构建，不依赖后端服务；内容集中在 content.js，方便日常维护。"] },
        { id: "structure", title: "内容结构", section: "02", body: ["个人介绍集中维护在 profile 对象中。常用资源由名称、分类、简介、链接和色标组成。", "项目条目支持简介、参与角色、成果、技术标签，以及各自的 Wiki 子页面。"] },
        { id: "maintenance", title: "维护记录", section: "03", body: ["添加项目时，在 projects 数组中增加一个条目，并为需要记录的主题添加 Wiki 页面。", "资源可以用页面上方的搜索框查找，也可以按分类浏览。站内页面通过地址栏中的 hash 导航。"] },
        { id: "deploy", title: "发布到 GitHub Pages", section: "04", body: ["将本目录推送到 GitHub 仓库。在仓库 Settings → Pages 中，选择从分支部署，并将目录设为根目录。", "保存后，GitHub Pages 会提供站点地址。项目仓库和个人站点仓库都可以部署；个人站点仓库通常命名为 username.github.io。"] }
      ]
    },
    {
      id: "diamond-continent-plus",
      name: "钻石大陆加豪版",
      kind: "Minecraft 整合包",
      status: "Wiki 整理中",
      year: "—",
      summary: "整理核心模组功能、语言文件翻译说明与游玩流程。",
      tags: ["Minecraft", "整合包", "汉化"],
      role: "整合包制作与资料整理",
      outcome: "把整合包相关说明整理成便于查阅的 Wiki。",
      description: "一个 Minecraft 整合包。在这里整理核心模组功能、翻译说明与游玩流程。",
      wikiTheme: "plain",
      pages: [
        {
          id: "translation-method",
          title: "如何将整合包翻译为不同语言",
          section: "01",
          description: "整理语言文件的位置、翻译键与多语言脚本的配置步骤。",
          headings: [
            { before: 0, id: "before-start", title: "开始之前" },
            { before: 2, id: "language-files", title: "语言资源文件" },
            { before: 4, id: "client-scripts", title: "客户端翻译脚本" },
            { before: 6, id: "language-registration", title: "注册目标语言" },
            { before: 7, id: "check-result", title: "检查翻译结果" }
          ],
          callouts: [1],
          snippets: [{ after: 6, language: "JavaScript", caption: "注册行示例（原文片段）", text: "ClientEvents.lang('en_us', e => {" }],
          body: [
            "本页根据钻石大陆加豪版的实例文件编写。语言文件主要位于 kubejs/assets 和 kubejs/client_scripts；动手前先备份整个 kubejs 文件夹。",
            "目前本整合包的 FTB 任务部分暂时不提供兼容。通过以下方法添加的语言不会翻译或兼容 FTB 任务内容。",
            "一、kubejs/assets：可参照 Minecraft 官方 Wiki 的资源包语言文件方法。在现有模组命名空间下找到 lang 文件夹，例如 kubejs/assets/<命名空间>/lang/zh_cn.json；按同样的目录位置新增目标语言 JSON 文件，例如 en_us.json。",
            "JSON 文件使用翻译键和值的对应关系。参照 zh_cn.json 中的键名，在新文件里保留相同的键，只填写该语言对应的文本。不要翻译或改动键名，并保持 JSON 的引号、逗号和转义格式正确。不同语言代码使用小写语言与地区格式，例如 en_us、ja_jp。",
            "二、kubejs/client_scripts：这部分使用 KubeJS 脚本注册语言，不能只新增 JSON。实例中的中文脚本位于 kubejs/client_scripts/src/zh_cn/，主要文件是 zh_cn.js 和 tooltip_zh_cn.js。为新语言新建对应目录，例如 src/en_us/，分别复制这两个文件并重命名为 en_us.js 和 tooltip_en_us.js。",
            "复制脚本后，需要把文件中声明的变量名和函数名改成该语言专属的名称，并同步修改脚本内对这些名称的引用，避免与其他语言脚本重复。主翻译文件和提示文字文件都要检查；如果新增多种语言，每种语言都使用各自独有的名称。不要改动翻译键、物品 ID、占位符或脚本功能逻辑。",
            "打开两个新脚本，在文件底部找到 ClientEvents.lang('zh_cn', e => {，将 zh_cn 改为目标语言简称。例如英文使用 ClientEvents.lang('en_us', e => {，日文使用 ClientEvents.lang('ja_jp', e => {。两个脚本都要修改注册语言代码；文件名、目录名和注册代码应保持一致。",
            "完成后，在启动器里将游戏语言切换到目标语言，检查 kubejs/assets 与 kubejs/client_scripts 添加的文本。若文本没有变化，核对语言代码、目录层级和 ClientEvents.lang 注册项；若启动时报脚本错误，恢复备份并检查变量名引用及语法。",
            "本整合包中不少内容的中文名称参考了不同的网络梗。如发现翻译问题，欢迎联系作者，也欢迎通过 PR 或 Issue 提交修正与建议。"
          ]
        },
        {
          id: "superflatcore",
          title: "SuperFlatCore",
          category: "核心模组",
          section: "03",
          description: "整合包核心模组的机器、资源生成方式与模组联动功能说明。",
          markdown: [
            "SuperFlatCore（简称 SFC）是《钻石大陆加豪版》的整合包核心模组，主要负责补充机器、资源生成方式，以及各模组之间的联动。本页说明游戏中实际能看到和使用的功能。",
            "",
            "## 新增机器与部件",
            "",
            "### 风力发电机",
            "",
            "SFC 添加了一台 LV 级风力发电机，外观、结构和运行动画沿用 Mekanism 风力发电机。机器上方需要能看到天空，且机器高度不能低于 Y=0。电力从机器正面输出。",
            "",
            "发电量按下式计算：",
            "",
            "`基础产能 × 高度效率 × 风能转子产出倍率`",
            "",
            "- Y=0 时高度效率为 35%，从 Y=0 到 Y=128 线性上升；Y≥128 时为 100%。",
            "- 转子提供“风能产出”倍率，不使用 GT 涡轮转子的涡轮效率属性。",
            "- 转子工作时会损耗耐久；有风且机器已满电时仍会损耗，但速度较慢。",
            "- GUI 显示机器高度、基础产能、实际产能，并提供转子槽和耐久条。",
            "",
            "### 风力转子",
            "",
            "SFC 新增 GT 材料部件 `wind_rotor`。有 GT 转子属性且满足材料生成条件的材料可以生成对应转子；转子的风能产出取自材料的转子属性。",
            "",
            "冲压机配方为：1 个 `gtceu:long_steel_rod` 加 4 个对应材料的双层板，16 EU、10 ticks。风机只接受 SFC 的风力转子。",
            "",
            "### 魔力压迫机",
            "",
            "这是一台没有 EU 输入、也不需要 EU 输出的 GT 多方块机器。它有两个模式，由结构 L 位置的方块决定。",
            "",
            "- **魔力灌注模式**：使用 Botania 的魔力灌注配方。L 位置放置对应配方的底座；没有指定底座的配方使用 `botania:mana_diamond_block`。底座只用于识别，不会被消耗。机器固定运行 40 ticks，可按物品数量并行，也能在同一批次处理多种灌注配方；此模式不能安装并行仓。",
            "- **魔力压迫模式**：L 位置固定使用 `botania:mana_void`。配方支持最多 6 个物品输入、4 个物品输出、3 个流体输入和 2 个流体输出；并行数由并行仓决定。",
            "",
            "结构至少需要一个 SFC 魔力输入仓。输入仓只接受 `technicalflowers:mana`，按 1 mB 对应 1 点魔力扣除。每个魔力仓容量为 512,000 mB。GUI 使用 Botania 风格的魔力条显示存量；JEI 中两种配方都会显示魔力需求，灌注配方也会显示底座物品。",
            "",
            "魔力压迫配方通过 KubeJS 注册，例如：",
            "",
            "```js",
            "ServerEvents.recipes(event => {",
            "  event.recipes.super.mana_oppression()",
            "    .itemInputs(",
            "      '4x gtceu:manasteel_dust',",
            "      '2x gtceu:treated_wood_dust',",
            "      '3x botania:mana_powder',",
            "      '2x gtceu:livingrock_dust'",
            "    )",
            "    .itemOutputs('11x gtceu:pig_iron_dust')",
            "    .duration(75)",
            "    .addData('superflatcore:mana', 3750)",
            "})",
            "```",
            "",
            "### 热交换器",
            "",
            "新增 GT 多方块热交换器配方类型。配方使用热流体和冷却介质进行换热，并输出配方指定的流体。使用非水冷却介质时，运行还会按配方用量消耗蒸馏水。具体配方可由整合包数据包或 KubeJS 添加。",
            "",
            "### 超临界蒸汽涡轮",
            "",
            "新增 IV 级多方块发电机和专用涡轮外壳。内置配方每运行 30 ticks 消耗 1,280 mB `gtceu:supercritical_steam`，发出 128 EU/t，并产出 8 mB 蒸馏水。后续可继续添加涡轮配方。",
            "",
            "### 放射性流体设备",
            "",
            "- Create 风格的放射性流体罐支持连接成罐体，每个罐体方块提供 16,000 mB 容量。",
            "- IV 级放射性流体输入仓和输出仓各有 256,000 mB 容量，只接受 `#oritong:radioactive_fluids` 标签中的流体。",
            "- 拆除放射性流体罐时，储存的放射性流体会产生 Mekanism 辐射；拆除大型罐体中的单个方块时，辐射量按其代表的存量比例计算。",
            "- AE2 的普通和创造型流体元件不能存入放射性流体。拆除存有放射性流体的 AE2 接口或样板供应器时也会释放辐射。",
            "- 大型离心机、大型流体提取机和 AtomicEmbersDecayed 反应堆结构支持放射性流体仓。反应堆拆解或事故发生时会按反应堆内流体量产生辐射。",
            "",
            "放射性流体由整合包加入 `#oritong:radioactive_fluids` 标签；SFC 不会自动把所有流体都视为放射性流体。",
            "",
            "### 维护仓与能源仓",
            "",
            "- 普通、洁净室、无菌洁净室可配置自动维护仓，以及创造型无菌洁净室自动维护仓，都能自动处理维护问题。普通变体可把配方时长调整到 0.5 倍至 1.5 倍；创造型范围为 0.001 倍至 100 倍。点击 GUI 的减号或加号调整，Shift/Ctrl 改变步长，Ctrl+Shift 直接设为范围端点。",
            "- GT 双输入仓和双输出仓从 LV 起注册，并按电压等级扩展物品槽数和流体容量。",
            "- 新增 262,144 A、1,048,576 A、4,194,304 A 激光输入/输出仓。",
            "- 新增 GTMThings 无线 64 A 能源输入/输出仓，以及 262,144 A、1,048,576 A、4,194,304 A 无线激光目标/源仓。无线仓使用 GTMThings 的无线能源池；放置时绑定玩家，也可以用数据棒绑定或解除绑定。",
            "- 新增 512,000 mB 魔力输入/输出仓和 256,000 mB 放射性流体输入/输出仓。",
            "",
            "### GTCEu 外接覆盖板",
            "",
            "- **超级无限水覆盖板**：每秒向相邻流体容器补水。",
            "- **空气输入覆盖板**：每秒向相邻流体容器输入 GT 空气。基础、进阶、精英、终极档分别为 600、3,000、10,000、20,000 mB/s；创造档使用最大整数速率。",
            "",
            "## 刚玉簇与资源生成",
            "",
            "SFC 注册土、木、水、火、金五种刚玉簇，每种有小型、中型、大型和完整簇四个阶段。完整簇被破坏时必定掉落对应的 GT 宝石 2 至 3 个，不受时运影响，也不要求特定工具；较小阶段不掉落宝石。",
            "",
            "### Create 注液器生长",
            "",
            "把对应的变质石放在注液器正下方，并在它下面放对应的 GTCEu 刚玉方块。对变质石注入至少 325 mB `technicalflowers:mana` 后，如果上方是空气，就会生成小型簇。若上方已有对应刚玉簇，则有机会长大：",
            "",
            "| 元素 | 首次生长用的变质石 | 下方刚玉方块 | 后续生长基底 |",
            "| --- | --- | --- | --- |",
            "| 水 | `botania:metamorphic_swamp_stone` | `gtceu:water_corundum_block` | 对应变质石或黑石 |",
            "| 木 | `botania:metamorphic_forest_stone` | `gtceu:wood_corundum_block` | 对应变质石或黑石 |",
            "| 火 | `botania:metamorphic_desert_stone` | `gtceu:fire_corundum_block` | 对应变质石或黑石 |",
            "| 土 | `botania:metamorphic_fungal_stone` | `gtceu:earth_corundum_block` | 对应变质石或黑石 |",
            "| 金 | `botania:metamorphic_mountain_stone` | `gtceu:metal_corundum_block` | 对应变质石或黑石 |",
            "",
            "小型升中型、中型升大型、大型升完整簇的成功率依次为 75%、65%、55%。每次有效注液都有 22% 概率把变质石变成黑石。黑石能继续催化已有簇生长，但不能用于从空气开始生成第一阶段。",
            "",
            "## 其他模组联动",
            "",
            "### Botania 与植物魔法",
            "",
            "- 泰拉凝聚板使用 SFC 导入的结构模板。结构成型时，板上方会出现一个使用魔力玻璃材质的曼德博海绵模型：以 45° 倾斜，持续旋转、变色，并在 1.75 倍至 2.5 倍之间变化大小。",
            "- 魔力灌注配方直接接入魔力压迫机；魔力需求和底座会显示在机器 GUI/JEI 中。",
            "- Ars Nouveau 的源质罐容量提高到 128,000 Source。",
            "- Ars Nouveau 的火焰精华右键会发射小型火球，并消耗一份精华。",
            "- Dominion Wand 获得 Botania Twig Wand 的交互和模式切换功能；潜行右键空气可切换模式。",
            "",
            "### Occultism 神秘学",
            "",
            "- 异界维度矿井使用 GTNN 的维度矿物池和权重产出，不再走 Occultism 自带的旧产出；GTNN 矿池中的 `gtceu:raw_bauxite` 和 `gtceu:raw_coal` 不会由矿井产出。",
            "- 异界石交易的输入改为黑石；异界树苗交易的输入改为 `botania:pure_daisy`，交易结果仍是对应的异界石或树苗。",
            "- 普通剪刀不再从异界树叶掉落树叶；使用 Manasteel Shears 或精准采集仍可取得树叶。",
            "",
            "### Mekanism、AtomicEmbers 与 MoreBurners",
            "",
            "- Mekanism 电力熔炼炉不再补充自动生成的原版熔炼配方，只读取配方管理器提供的配方。",
            "- AtomicEmbersDecayed 反应堆使用 SFC 的标准结构，并要求输出位置下方有放射性流体罐。反应堆拆解或事故会产生 Mekanism 辐射；事故可进入 EzUnclear 的确认流程。",
            "- MoreBurners 的余烬燃烧器每 5 秒尝试消耗 `100 × MoreBurners 配置中的 Ember Cost`，随后工作 5 秒；余烬不足时跳过该轮。运行中的燃烧器可为正下方的 Embers 迷你锅炉供热。",
            "",
            "### Create、GregTech 与其他配方调整",
            "",
            "- GT 风力转子按材料生成冲压机配方，见“风力转子”。",
            "- Industrial Foregoing 的发酵站、洗矿机、流体筛粉机及菌丝网络发电机配方会从 JEI 的自定义配方列表中隐藏。此处理影响 JEI 展示，不会直接删除服务器配方管理器中的配方。",
            "- Super Factory Manager 的坠落铁砧 JEI 页面把钢块显示为消耗的成型材料。",
            "- GTCEu 多方块结构预览支持右键拖动平移；原有左键旋转和滚轮缩放仍可用。",
            "- 带有 `#forge:springs` 或 `#forge:small_springs` 标签的掉落实体落地时会反弹。",
            "- Industrial Foregoing 的 Infinity Nuke 改用 `ifeu:dragon_star` 点燃，成功点燃会消耗一颗 Dragon Star；打火石不再点燃它。",
            "- Industrial Foregoing 的 Latex Processing Unit 接受 SFC 的乳胶流体 `oritong:latex`。",
            "",
            "## 玩家物品与状态效果",
            "",
            "- **结构检测工具**：右键 GTCEu 多方块控制器，在聊天栏查看成型状态或错误位置；错误方块会高亮显示，手持工具时可继续观察。潜行右键空气可切换 Cable Facades 的伪装渲染。工具提示标明材质来源为 GTOCore。",
            "- **员工伴侣**：右键召唤一个 Minopp 员工投影；右键投影切换行为模式，潜行右键移除。投影使用随机编号，极低概率显示为 ChocoFox。",
            "- **别碰我**：连续右键会逐阶段改变物品外观并触发音效、灰度/异常视觉效果；10 秒未继续操作会复位。推进到最后阶段后再次使用会崩溃当前客户端，这是刻意设计的恶作剧效果，不会代替正常游戏道具使用。",
            "- **Machine Soul Joy**：跳上符合条件的 GTCEu 机器时有机会触发短暂的时间加速；发电机类机器则可能短暂减速。",
            "- **Machine Soul Displeasure**：周期性影响附近机器的配方速度；普通机器减速，发电机类机器可能获得短暂加速。Jade 可显示倍率和剩余时间。",
            "- 三种 RainRot Five Pebbsi 饮料即使饱食度已满也能饮用；饮用后获得 1 分钟速度效果和 3 分钟 Machine Soul Joy，并返还 Magnalium Foil 与 Aluminium Ring。",
            "- `rainrot:data_pearl` 最大堆叠数提高到 64。",
            "- 潜行右键主手中的 `beyonddimensions:shattered_space_time_crystallization`，会消耗一颗水晶，为背包或饰品栏找到的第一瓶 Time in a Bottle 增加 15 分钟。",
            "",
            "## 配方工具",
            "",
            "GTCEu KubeJS 配方支持两种附加 Modifier：",
            "",
            "- `GTRecipeModifiers.MULTIPLERECIPE`：让支持该 Modifier 的多方块机器使用 SFC 的多配方批处理逻辑。",
            "- `GTRecipeModifiers.PROPORTIONAL_INPUT`：按整数倍检查物品和流体输入是否与配方用量成比例；未满足比例条件的批次会被消耗，但不产生配方输出。",
            "",
            "## 配置",
            "",
            "风力发电机配置位于 `config/superflatcore-common.toml`：",
            "",
            "| 配置项 | 默认值 | 作用 |",
            "| --- | ---: | --- |",
            "| `windGeneratorBaseProduction` | 60 EU/t | 风力发电机基础产能；更改后新放置的发电机使用新值 |",
            "| `windGeneratorActiveRotorWear` | 6 / 秒 | 正在发电时转子的耐久损耗 |",
            "| `windGeneratorFullRotorWear` | 2 / 秒 | 有风、满足工作条件但储能已满时的转子耐久损耗 |",
            "",
            "## 依赖",
            "",
            "SFC 是整合包核心模组，不面向缺少配套模组的独立安装。GTCEu、Create、Mekanism、Botania、Occultism、GTNN、MoreBurners 等依赖均按必需项加载；完整依赖与版本范围以模组包内的 `META-INF/mods.toml` 为准。"
          ].join("\n")
        },
        {
          id: "workflow",
          title: "流程梳理",
          section: "02",
          status: "整理中",
          description: "待补充的游玩说明与流程记录，目前为整理计划。",
          body: [
            "本页用于补充钻石大陆加豪版本体说明中没有覆盖的内容，记录游玩时容易遗漏的规则、前置条件、注意事项与常见问题。",
            "如果某个机制、物品或任务在整合包内没有写清楚，可以在这里补充背景、触发条件、获取方式和解决方法，方便之后查阅。",
            "本页也会整理一套相对固定的游玩流程，按照准备阶段、前期发展、中期推进和后期目标记录推荐顺序。流程内容以实际游玩体验为准，遇到版本更新时需要同步检查。",
            "后续补充流程时，建议每一步写明目标、前置条件、主要操作和完成后的下一步；如果存在多种可行路线，也应标注路线差异和适用情况。"
          ]
        }
      ]
    }
  ],
  participations: [],
  gallery: {
    title: "个人图库",
    description: "这里收录了我的形象约稿，记录不同画师笔下的我。感谢每一位画师的创作。",
    rightsNotice: "所有稿件均禁止投喂 AI。未经许可，请勿转载、商用或挪作他用。",
    artworks: [
      { image: "assets/gallery/character-sheet.png", title: "个人形象设定图", artist: "鰹ノえぼシ", artistUrl: "https://www.eboshi-official.com/", alt: "哦里冻的个人形象设定图" },
      { image: "assets/gallery/choco-illustration.png", title: "一枚小兽", artist: "伊伊子哦", artistUrl: "https://huajia.163.com/main/profile/pB09n5lE?", alt: "伊伊子哦绘制的可爱小兽" },
      { image: "assets/gallery/little-beast.png", title: "中秋贺图", artist: "葉碧岚", artistUrl: "https://huajia.163.com/main/profile/grk2zqQE?", alt: "葉碧岚绘制的中秋主题贺图" },
      { image: "assets/gallery/moon-festival.png", title: "一个芝士球", artist: "芋间凉叙", artistUrl: "https://space.bilibili.com/1939969303", alt: "芋间凉叙绘制的芝士球主题插画" },
      { image: "assets/gallery/cheese-ball.png", title: "一张可爱小兽", artist: "Decol", artistUrl: "https://huajia.163.com/main/profile/MrALqa6E?", alt: "Decol绘制的可爱小兽" },
      { image: "assets/gallery/mountain-peak.jpg", title: "横插", artist: "鰹ノえぼシ", artistUrl: "https://www.eboshi-official.com/", alt: "鰹ノえぼシ绘制的横版插画" }
    ]
  }
};
